profiles:
  prpl-template:
    platform: prpl
    prompt_regex: "(?m)^root@prplOS:.*# "
    login_regex: "(?mi)^login:\\s*$"
    password_regex: "(?mi)^password:\\s*$"
    ready_probe: "echo __READY__${nonce}"
    uart:
      baud: 115200
      data_bits: 8
      parity: N
      stop_bits: 1
      flow_control: none
      xonxoff: false
  opi-shell:
    platform: shell
    prompt_regex: ".*[$#] $"
    login_regex: "(?mi)^.*login:\\s*$"
    password_regex: "(?mi)^password:\\s*$"
    user_env: "SW_OPI_U"
    pass_env: "SW_OPI_P"
    ready_probe: "echo __READY__${nonce}"
    uart:
      baud: 115200
      data_bits: 8
      parity: N
      stop_bits: 1
      flow_control: none
      xonxoff: false

targets:
  - act_no: 1
    com: COM0
    alias: default+1
    profile: prpl-template
    device_by_id: /dev/serial/by-id/target0
  - act_no: 2
    com: COM1
    alias: default+2
    profile: prpl-template
    device_by_id: /dev/serial/by-id/target1
  - act_no: 3
    com: COM2
    alias: default+3
    profile: opi-shell
    device_by_id: /dev/serial/by-id/target2
  - act_no: 4
    com: COM3
    alias: default+4
    profile: prpl-template
    device_by_id: /dev/serial/by-id/target3
