name: Policy Check
on: [pull_request]

permissions:
  contents: read

jobs:
  policy:
    uses: hamanpaul/paulsha-conventions/.github/workflows/reusable-policy-check.yml@ee87a6d5ed91209d944934a2559f4f2622fd1ac2 # v1.0.10
    with:
      policy_profile: flat
      policy_version: "1.0.10"
      policy_engine_ref: ee87a6d5ed91209d944934a2559f4f2622fd1ac2
