name: Policy Check
on: [pull_request]

permissions:
  contents: read

jobs:
  policy:
    uses: hamanpaul/paulsha-conventions/.github/workflows/reusable-policy-check.yml@484f963adddf384d30fa0dd85aef35dddf822ee7
    with:
      policy_profile: flat
      policy_version: "1.0.5"
      policy_engine_ref: 484f963adddf384d30fa0dd85aef35dddf822ee7
