name: Policy Check
on: [pull_request]

permissions:
  contents: read

jobs:
  policy:
    uses: hamanpaul/paulsha-conventions/.github/workflows/reusable-policy-check.yml@77a3e8381eeced9dbba623e450ed6a5c1fcc7b18
    with:
      policy_profile: flat
      policy_version: "1.0.4"
      policy_engine_ref: 77a3e8381eeced9dbba623e450ed6a5c1fcc7b18
